-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceWhoIsOnline/maintenance/db/sql/bs_whoisonline.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE bs_whoisonline (
  wo_id BIGSERIAL NOT NULL,
  wo_user_id INT NOT NULL,
  wo_user_name TEXT DEFAULT '' NOT NULL,
  wo_user_real_name TEXT DEFAULT '' NOT NULL,
  wo_page_id INT NOT NULL,
  wo_page_namespace INT NOT NULL,
  wo_page_title TEXT NOT NULL,
  wo_action TEXT NOT NULL,
  wo_log_ts TIMESTAMPTZ DEFAULT '0' NOT NULL,
  PRIMARY KEY(wo_id)
);
