-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceWhoIsOnline/maintenance/db/sql/bs_whoisonline.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_whoisonline (
  wo_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  wo_user_id INTEGER UNSIGNED NOT NULL,
  wo_user_name BLOB DEFAULT '' NOT NULL,
  wo_user_real_name BLOB DEFAULT '' NOT NULL,
  wo_page_id INTEGER UNSIGNED NOT NULL,
  wo_page_namespace INTEGER NOT NULL,
  wo_page_title BLOB NOT NULL, wo_action BLOB NOT NULL,
  wo_log_ts BLOB DEFAULT '0' NOT NULL
);
